### ISSUE TITLE
Implement Player Management

### ISSUE THREAD

**Issue by power-fungus** [Haskell-Praxis/core-catcher#14]
The player should be identifiable by name and enter a name before their game.

Player should be able to reconnect.

**Comment by fendor** [comment]
This needs some discussion:
Should information like this be saved in the connection? For this, we could expand the IsConnection Type class.

Other things like reconnect after disconnect have to be implemented via the Protocol, we need a definition for this reason. This would be helpful in a number of ways, for example, a chat where the players can talk to each other.

**Comment by power-fungus** [comment]
implemented in the latest player-management commit
