### ISSUE TITLE
Reduce boiler-plate code in Network.Protocol with TemplateHaskell

### ISSUE THREAD

**Issue by power-fungus** [Haskell-Praxis/core-catcher#22]
Have fun @fendor!

**Comment by power-fungus** [comment]
looks good!!

**Comment by fendor** [comment]
It works already for `Map` like instances. 
I still got to do more error checking, for example check for a given type, if it implements `IsMap` instead of checking for a specific specific Syntax Pattern

**Comment by power-fungus** [comment]
With PR #28 and #27 this is implemented
