### ISSUE TITLE
Error handling if incorrect json sent between server and client

### ISSUE THREAD

**Issue by power-fungus** [Haskell-Praxis/core-catcher#26]
How to handle the case that the json sent between server and client cannot be parsed in one of the sides?

**Comment by fendor** [comment]
Log the error. 
An alternative is, that the client somehow notifies the server. But I think, there is only so much one can do

**Comment by power-fungus** [comment]
"Log" in a sense that user sees something or only as a js-log?

**Comment by fendor** [comment]
Both is possible, if we want the user to file a bug report, then yes, display the message including a link to the issue page.
It would also be possible to publish the error message to hastebin and the user should attach this link in our issue tracker.

But the other way would work well for now.

**Comment by power-fungus** [comment]
The auto-reporting is a nice idea :)

But will most likely not be used since the protocol can easily be synced. The question is how to deal with the parsed `Maybe`.

**Comment by power-fungus** [comment]
The auto-reporting is a nice idea :)

But will most likely not be used since the protocol can easily be synced. The question is how to deal with the parsed `Maybe`.

**Comment by fendor** [comment]
We can create an issue for this ;) 

You are right, it is probably not our concern.

**Comment by power-fungus** [comment]
We assume that the protocol-modules are always synced perfectly :)

Then, we just ignore the `Nothing` part of the maybe after parsing
