### ISSUE TITLE
remove logging of `CloseRequest 1001 ""`

### ISSUE THREAD

**Issue by power-fungus** [Haskell-Praxis/core-catcher#35]
I have no idea where this is printed, however it should be removed.

@fendor any ideas?

**Comment by fendor** [comment]
Good question, i would guess, it is some logging by WAI?

**Comment by power-fungus** [comment]
Maybe, how to fix it?

**Comment by fendor** [comment]
well, my suggestion would be to delete ".stack_work/" and build without the debugger options, which should be "stack build --profile". 
Therefore, just invoke "stack build". If that doesn't fix it, i will go ask in the IRC channels and post their answer here

**Comment by power-fungus** [comment]
I don't get it...

**Comment by power-fungus** [comment]
the issue was, that receiveData thros an Exception, which needed to be caught.
