### ISSUE TITLE
Derivation of the Elm Protocol should generate only valid elm code

### ISSUE THREAD

**Issue by fendor** [Haskell-Praxis/core-catcher#8]
Due the fact that the library elm-bridge is out of date in some aspects, the generated code can not successfully compiled via `elm-make`.

A import does not expose a certain function anymore which causes the problems. Also it might be a good idea, to execute `elm-format` on the generated output file.

**Comment by power-fungus** [comment]
`writeFileUtf8 "fromtend/Protocol.elm" . unlines . filter (not . contains "(:=)") . lines $ elmProtocolModule`

**Comment by fendor** [comment]
Compiler error is fixed.
Might still be worth it the time to execute elm-format automatically after code generation
